### PR TITLE
CellStar package 1.3

### PR DESCRIPTION
**Pull request by Fafa87**
This pull request updates the initial CellStar version to all the improvement made from that time:
- much better parameter fitting
- very significant speed up
- a lot of bugs fixed
- example usages link
- updated Readme.rst

Additionally it cleans up code and provide package-level unit tests.

### CODE REVIEW

**Comment by Fafa87** [comment]
As to submitting package to PyPI, should we do it?

**Comment by mcquin** [comment]
@Fafa87 Yes! This should be published to PyPI before we merge the changes to CellProfiler, CellProfiler-tutorials, and centrosome.

Additionally, could you or your organization accept control of this project? We are working with very limited resources and aren't able to take responsibility for another project. The project will be best served by people with strong understanding of the code base and underlying algorithms; qualities which you, as the primary author, certainly have. We'll help facilitate transfer of ownership from our CellProfiler organization to yours.

**Comment by Fafa87** [comment]
I would actually love to accept control of cellstar ;)
How can we do it?

PS. I would not say limited, there is Allen and You. It's like a big step up in CellProfiler history :)

**Comment by mcquin** [comment]
> I would actually love to accept control of cellstar ;)

Excellent!! 🎉 

> How can we do it?

The [documentation on transferring repositories](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) makes it seem fairly straightforward. I have Owner permissions on CellProfiler. I need to be granted permission to create repositories in the destination organization.

Once transfer is initiated, you should receive an email confirming you want to accept the transfer. The email expires in 24. We can work together to coordinate the transfer and ensure it goes smoothly. :)

> PS. I would not say limited, there is Allen and You. It's like a big step up in CellProfiler history :)

Yeah! It's exciting!

**Comment by Fafa87** [comment]
> I need to be granted permission to create repositories in the destination organization.

I would like it to go to my personal account. I can't find a way to grant any permissions. 
...
From what I've read it seems that in case of "to user" transfer you just click transfer with no permission needed. Give it a try.

**Comment by Fafa87** [comment]
There may also be a problem because I have forked cellstar. In that case please merge this PR and let me know. I will remove my fork so you can try to transfer again.

**Comment by mcquin** [comment]
Sure thing!

I think you'll have to delete your fork before transferring. Check your email: you should have permissions to transfer this repository to your own account.

**Comment by Fafa87** [comment]
Success! Thanks!

**Comment by mcquin** [comment]
Nice! Happy programming! :)

**Pull request merged**
